# Generated by Django 5.0.4 on 2024-07-29 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_post_category_en_us_post_category_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='created_at_en_us',
        ),
        migrations.RemoveField(
            model_name='post',
            name='created_at_ru',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_type_en_us',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_type_ru',
        ),
    ]
